// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-17
// Task: 创建API服务器主入口，整合所有路由

/**
 * API服务器主入口
 * 
 * 整合用户管理和组织管理API路由
 */

import express, { Express } from 'express';
import Database from 'better-sqlite3';
import { createUserRoutes } from './user-routes.js';
import { createOrganizationRoutes } from './organization-routes.js';

/**
 * 创建API应用
 */
export function createApiApp(db: Database.Database): Express {
  const app = express();
  
  // 中间件
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));
  
  // CORS
  app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    
    if (req.method === 'OPTIONS') {
      return res.sendStatus(200);
    }
    
    next();
  });
  
  // 健康检查
  app.get('/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
  });
  
  // 挂载路由
  app.use('/api/users', createUserRoutes(db));
  app.use('/api/organizations', createOrganizationRoutes(db));
  
  // 404处理
  app.use((req, res) => {
    res.status(404).json({
      error: {
        code: 'NOT_FOUND',
        message: '请求的资源不存在',
      },
    });
  });
  
  // 错误处理
  app.use((err: any, req: any, res: any, next: any) => {
    console.error('Server error:', err);
    res.status(500).json({
      error: {
        code: 'INTERNAL_ERROR',
        message: err.message || '服务器内部错误',
      },
    });
  });
  
  return app;
}

/**
 * 启动API服务器
 */
export function startApiServer(db: Database.Database, port: number = 3000): void {
  const app = createApiApp(db);
  
  app.listen(port, () => {
    console.log(`✅ M6 API服务器已启动: http://localhost:${port}`);
    console.log(`   健康检查: http://localhost:${port}/health`);
    console.log(`   用户API: http://localhost:${port}/api/users`);
    console.log(`   组织API: http://localhost:${port}/api/organizations`);
  });
}
