// Generated by Qoder AI (Model: claude-sonnet-4-20250514) - 2025-10-14
// Task: 增强CLI diff命令显示格式（彩色输出、表格展示）

/**
 * 配置差异分析命令
 * 负责对比当前系统配置和将要应用的配置计划，展示差异信息
 *
 * 核心职责：
 * - 读取本地配置计划文件
 * - 调用各个适配器进行差异分析
 * - 以表格和彩色形式展示变更详情
 * - 提供下一步操作指引
 */

import chalk from 'chalk';
import fs from 'fs/promises';
import path from 'path';
import Table from 'cli-table3';
import { createAdapter } from '@meteor-shower/adapters';

/**
 * 变更详情接口
 * 描述单个配置文件的变更信息
 */
interface ChangeDetail {
  path: string;                       // 文件路径
  kind: 'create' | 'update' | 'delete';  // 变更类型
  tool: string;                       // 所属工具
  size?: string;                      // 文件大小
  description?: string;               // 变更描述
}

/**
 * 差异分析命令主函数
 * 
 * 业务流程：
 * 1. 读取配置计划 - 从 .meteor-shower/config-plan.json 读取
 * 2. 显示配置信息 - 展示模板、工具集、变量数量
 * 3. 分析差异 - 调用每个工具的适配器进行 plan()
 * 4. 统计汇总 - 按类型统计变更数量（新建/更新/删除）
 * 5. 展示结果 - 使用表格和颜色编码展示详细变更
 * 6. 提供指引 - 告知用户如何应用配置
 */
  console.log(chalk.cyan.bold('\n🔍 分析配置差异\n'));
  console.log(chalk.gray('─'.repeat(60)));
  
  try {
    // ========== 读取配置计划 ==========
    const planPath = path.join(process.cwd(), '.meteor-shower', 'config-plan.json');
    const planContent = await fs.readFile(planPath, 'utf-8');
    const configPlan = JSON.parse(planContent);
    
    // 显示配置信息
    console.log(chalk.white('\n配置计划信息:'));
    console.log(chalk.gray(`  模板:     ${chalk.cyan(configPlan.template)}`));
    console.log(chalk.gray(`  工具集:   ${chalk.cyan(configPlan.toolset.join(', '))}`));
    console.log(chalk.gray(`  变量数:   ${chalk.cyan(Object.keys(configPlan.variables).length)}`));
    
    // ========== 对每个工具进行差异分析 ==========
    // 调用适配器的 plan() 方法，以 dryRun 模式获取变更详情
    const allChanges: ChangeDetail[] = [];
    
    console.log(chalk.gray('\n正在分析配置差异...'));
    
    // 为每个工具创建适配器并进行分析
    for (const tool of configPlan.toolset) {
      const adapter = createAdapter(tool);
      const diffResult = await adapter.plan({
        target: tool,
        dryRun: true,  // 干跑模式，不实际修改文件
        variables: configPlan.variables
      });
      
      // 为每个变更添加工具信息
      const changesWithTool = diffResult.changes.map((change: any) => ({
        ...change,
        tool: tool
      }));
      
      allChanges.push(...changesWithTool);
    }
    
    // ========== 统计变更信息 ==========
    // 按变更类型分类统计
    const createCount = allChanges.filter(c => c.kind === 'create').length;
    const updateCount = allChanges.filter(c => c.kind === 'update').length;
    const deleteCount = allChanges.filter(c => c.kind === 'delete').length;
    
    // 显示统计摘要
    console.log(chalk.cyan('\n📊 变更统计:\n'));
    const statsTable = new Table({
      head: [chalk.white.bold('类型'), chalk.white.bold('数量'), chalk.white.bold('说明')],
      colWidths: [15, 10, 35],
      style: {
        head: [],
        border: ['gray']
      }
    });
    
    if (createCount > 0) {
      statsTable.push([
        chalk.green('✨ 新建'),
        chalk.green.bold(createCount),
        chalk.gray('将创建新配置文件')
      ]);
    }
    
    if (updateCount > 0) {
      statsTable.push([
        chalk.yellow('🔄 更新'),
        chalk.yellow.bold(updateCount),
        chalk.gray('将更新现有配置文件')
      ]);
    }
    
    if (deleteCount > 0) {
      statsTable.push([
        chalk.red('🗑️  删除'),
        chalk.red.bold(deleteCount),
        chalk.gray('将删除配置文件')
      ]);
    }
    
    statsTable.push([
      chalk.cyan.bold('总计'),
      chalk.cyan.bold(allChanges.length),
      chalk.gray('配置文件总数')
    ]);
    
    console.log(statsTable.toString());
    
    // ========== 显示详细变更表格 ==========
    // 按工具分组展示变更列表
    if (allChanges.length > 0) {
      console.log(chalk.cyan('\n📋 详细变更列表:\n'));
      
      const changesTable = new Table({
        head: [
          chalk.white.bold('操作'),
          chalk.white.bold('工具'),
          chalk.white.bold('文件路径')
        ],
        colWidths: [8, 12, 50],
        style: {
          head: [],
          border: ['gray']
        },
        wordWrap: true
      });
      
      // 按工具分组，便于用户按工具查看变更
      const groupedByTool: Record<string, ChangeDetail[]> = {};
      allChanges.forEach(change => {
        if (!groupedByTool[change.tool]) {
          groupedByTool[change.tool] = [];
        }
        groupedByTool[change.tool].push(change);
      });
      
      // 为每个工具添加变更
      Object.entries(groupedByTool).forEach(([tool, changes]) => {
        changes.forEach((change, index) => {
          const kindIcon = getKindIcon(change.kind);
          const kindColor = getKindColor(change.kind);
          
          changesTable.push([
            chalk[kindColor](kindIcon),
            index === 0 ? chalk.cyan.bold(tool.toUpperCase()) : '',
            chalk.gray(change.path)
          ]);
        });
      });
      
      console.log(changesTable.toString());
    }
    
    // 显示文件位置信息
    console.log(chalk.cyan('\n📁 文件位置说明:\n'));
    const locationTable = new Table({
      colWidths: [20, 50],
      style: {
        border: ['gray']
      }
    });
    
    locationTable.push(
      [chalk.yellow('~/.gemini/'), chalk.gray('Gemini 全局配置目录')],
      [chalk.yellow('~/.claude/'), chalk.gray('Claude 全局配置目录')],
      [chalk.yellow('./.cursor/'), chalk.gray('Cursor 项目配置目录')],
      [chalk.yellow('./'), chalk.gray('项目根目录配置文件')]
    );
    
    console.log(locationTable.toString());
    
    // 下一步提示
    console.log(chalk.cyan('\n🎯 下一步操作:\n'));
    console.log(chalk.white('  1. 检查上述变更是否符合预期'));
    console.log(chalk.white('  2. 运行 ' + chalk.yellow.bold('ms apply') + ' 应用这些变更'));
    console.log(chalk.white('  3. 运行 ' + chalk.yellow.bold('ms apply --dry-run') + ' 模拟应用过程'));
    console.log(chalk.gray('\n─'.repeat(60)));
    console.log('');
    
  } catch (error: any) {
    console.log(chalk.gray('\n─'.repeat(60)));
    if (error.code === 'ENOENT') {
      console.error(chalk.red.bold('\n❌ 错误: 未找到配置计划文件\n'));
      console.log(chalk.yellow('💡 建议操作:'));
      console.log(chalk.white('  1. 运行 ' + chalk.cyan.bold('ms init') + ' 初始化配置'));
      console.log(chalk.white('  2. 完成配置向导后再运行 diff 命令'));
    } else {
      console.error(chalk.red.bold('\n❌ 分析配置差异失败\n'));
      console.error(chalk.red('错误详情:'), error.message);
      if (error.stack) {
        console.log(chalk.gray('\n堆栈跟踪:'));
        console.log(chalk.gray(error.stack));
      }
    }
    console.log('');
  }
}

/**
 * 根据变更类型获取图标
 */
function getKindIcon(kind: string): string {
  switch (kind) {
    case 'create': return '✨';
    case 'update': return '🔄';
    case 'delete': return '🗑️';
    default: return '❓';
  }
}

/**
 * 根据变更类型获取颜色
 */
function getKindColor(kind: string): 'green' | 'yellow' | 'red' | 'gray' {
  switch (kind) {
    case 'create': return 'green';
    case 'update': return 'yellow';
    case 'delete': return 'red';
    default: return 'gray';
  }
}
