// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-15
// Task: M6 Phase1 - A3: 数据治理功能 - 审计日志类型定义

import { Action, ResourceType } from './types.js';

/**
 * 审计事件类型
 */
export enum AuditEventType {
  /** 用户登录 */
  USER_LOGIN = 'user_login',
  
  /** 用户登出 */
  USER_LOGOUT = 'user_logout',
  
  /** 创建资源 */
  RESOURCE_CREATE = 'resource_create',
  
  /** 读取资源 */
  RESOURCE_READ = 'resource_read',
  
  /** 更新资源 */
  RESOURCE_UPDATE = 'resource_update',
  
  /** 删除资源 */
  RESOURCE_DELETE = 'resource_delete',
  
  /** 分享资源 */
  RESOURCE_SHARE = 'resource_share',
  
  /** 权限变更 */
  PERMISSION_CHANGE = 'permission_change',
  
  /** 配额变更 */
  QUOTA_CHANGE = 'quota_change',
  
  /** 订阅变更 */
  SUBSCRIPTION_CHANGE = 'subscription_change',
}

/**
 * 审计日志条目
 */
export interface AuditLogEntry {
  /** 日志ID */
  id: string;
  
  /** 事件类型 */
  eventType: AuditEventType;
  
  /** 执行操作的用户ID */
  userId: string;
  
  /** 资源类型（可选） */
  resourceType?: ResourceType;
  
  /** 资源ID（可选） */
  resourceId?: string;
  
  /** 操作类型（可选） */
  action?: Action;
  
  /** 操作前数据（可选） */
  before?: Record<string, any>;
  
  /** 操作后数据（可选） */
  after?: Record<string, any>;
  
  /** 额外元数据 */
  metadata?: Record<string, any>;
  
  /** IP地址 */
  ipAddress?: string;
  
  /** User Agent */
  userAgent?: string;
  
  /** 操作是否成功 */
  success: boolean;
  
  /** 失败原因（如果失败） */
  failureReason?: string;
  
  /** 创建时间戳 */
  timestamp: Date;
}

/**
 * 审计日志查询条件
 */
export interface AuditLogQuery {
  /** 用户ID */
  userId?: string;
  
  /** 事件类型 */
  eventType?: AuditEventType;
  
  /** 资源类型 */
  resourceType?: ResourceType;
  
  /** 资源ID */
  resourceId?: string;
  
  /** 开始时间 */
  startDate?: Date;
  
  /** 结束时间 */
  endDate?: Date;
  
  /** 是否只查询成功的操作 */
  successOnly?: boolean;
  
  /** 是否只查询失败的操作 */
  failureOnly?: boolean;
  
  /** 分页 - 页码（从1开始） */
  page?: number;
  
  /** 分页 - 每页条数 */
  pageSize?: number;
}

/**
 * 审计日志查询结果
 */
export interface AuditLogQueryResult {
  /** 日志条目 */
  entries: AuditLogEntry[];
  
  /** 总数 */
  total: number;
  
  /** 当前页 */
  page: number;
  
  /** 每页条数 */
  pageSize: number;
  
  /** 总页数 */
  totalPages: number;
}
