// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-15
// Task: M6 Phase1 - A3: 数据治理功能 - 权限矩阵类型定义

/**
 * 用户角色枚举
 */
export enum UserRole {
  /** 企业管理员 - 拥有所有权限 */
  ENTERPRISE_ADMIN = 'enterprise_admin',
  
  /** 部门管理员 - 管理部门资源 */
  DEPARTMENT_ADMIN = 'department_admin',
  
  /** 团队管理员 - 管理团队资源 */
  TEAM_ADMIN = 'team_admin',
  
  /** 普通成员 */
  MEMBER = 'member',
  
  /** 访客 - 只读权限 */
  GUEST = 'guest',
}

/**
 * 资源类型
 */
export enum ResourceType {
  /** 工具配置 */
  TOOL = 'tool',
  
  /** 模板 */
  TEMPLATE = 'template',
  
  /** 用户 */
  USER = 'user',
  
  /** 组织 */
  ORGANIZATION = 'organization',
  
  /** 使用统计 */
  USAGE_STATS = 'usage_stats',
  
  /** 订阅 */
  SUBSCRIPTION = 'subscription',
}

/**
 * 操作类型
 */
export enum Action {
  /** 创建 */
  CREATE = 'create',
  
  /** 读取 */
  READ = 'read',
  
  /** 更新 */
  UPDATE = 'update',
  
  /** 删除 */
  DELETE = 'delete',
  
  /** 分享 */
  SHARE = 'share',
  
  /** 管理 */
  MANAGE = 'manage',
}

/**
 * 权限字符串格式: resource:action
 * 例如: "tool:create", "template:read", "user:manage"
 */
export type Permission = `${ResourceType}:${Action}`;

/**
 * 权限检查结果
 */
export interface PermissionCheckResult {
  /** 是否有权限 */
  allowed: boolean;
  
  /** 拒绝原因（如果无权限） */
  reason?: string;
  
  /** 用户角色 */
  role: UserRole;
  
  /** 请求的权限 */
  permission: Permission;
}

/**
 * 资源所有权信息
 */
export interface ResourceOwnership {
  /** 资源ID */
  resourceId: string;
  
  /** 资源类型 */
  resourceType: ResourceType;
  
  /** 所有者用户ID */
  ownerId: string;
  
  /** 所属组织ID（可选） */
  organizationId?: string;
  
  /** 是否公开 */
  isPublic?: boolean;
}

/**
 * 权限上下文
 */
export interface PermissionContext {
  /** 用户ID */
  userId: string;
  
  /** 用户角色 */
  userRole: UserRole;
  
  /** 所属组织ID（可选） */
  organizationId?: string;
  
  /** 请求的操作 */
  action: Action;
  
  /** 目标资源类型 */
  resourceType: ResourceType;
  
  /** 目标资源（可选） */
  resource?: ResourceOwnership;
}
