// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-15
// Task: M6 Phase5 - 功能对比表数据模型和CLI展示

import chalk from 'chalk';
import { UserTier, TIER_LIMITS } from '../types.js';
import { Feature, FeatureManager } from '../features/feature-flags.js';
import { QuotaType, QUOTA_LIMITS } from '../quota/quota-manager.js';

/**
 * 功能分类
 */
export enum FeatureCategory {
  /** 基础功能 */
  BASIC = 'basic',
  /** 配额限制 */
  QUOTA = 'quota',
  /** 高级功能 */
  ADVANCED = 'advanced',
  /** 协作功能 */
  COLLABORATION = 'collaboration',
  /** 安全与合规 */
  SECURITY = 'security',
  /** 支持服务 */
  SUPPORT = 'support',
}

/**
 * 功能对比项
 */
export interface ComparisonItem {
  /** 功能名称 */
  name: string;
  /** 功能分类 */
  category: FeatureCategory;
  /** 功能描述 */
  description?: string;
  /** 各层级的值 */
  values: Record<UserTier, string | number | boolean>;
  /** 高亮显示（重要功能） */
  highlight?: boolean;
}

/**
 * 功能对比数据
 */
export const FEATURE_COMPARISON: ComparisonItem[] = [
  // 基础功能
  {
    name: '工具配置数量',
    category: FeatureCategory.BASIC,
    description: '可配置的AI工具数量',
    values: {
      [UserTier.FREE]: '3个',
      [UserTier.PROFESSIONAL]: '无限',
      [UserTier.TEAM]: '无限',
      [UserTier.ENTERPRISE]: '无限',
    },
    highlight: true,
  },
  {
    name: '云端模板',
    category: FeatureCategory.BASIC,
    description: '可保存的云端模板数量',
    values: {
      [UserTier.FREE]: '5个',
      [UserTier.PROFESSIONAL]: '无限',
      [UserTier.TEAM]: '无限',
      [UserTier.ENTERPRISE]: '无限',
    },
    highlight: true,
  },
  {
    name: '模板分享',
    category: FeatureCategory.BASIC,
    description: '每月可分享的模板次数',
    values: {
      [UserTier.FREE]: '10次/月',
      [UserTier.PROFESSIONAL]: '100次/月',
      [UserTier.TEAM]: '100次/月',
      [UserTier.ENTERPRISE]: '无限',
    },
  },
  
  // 配额限制
  {
    name: '能力验证次数',
    category: FeatureCategory.QUOTA,
    description: '每月可执行的能力验证次数',
    values: {
      [UserTier.FREE]: '20次/月',
      [UserTier.PROFESSIONAL]: '500次/月',
      [UserTier.TEAM]: '2000次/月',
      [UserTier.ENTERPRISE]: '无限',
    },
    highlight: true,
  },
  {
    name: '存储空间',
    category: FeatureCategory.QUOTA,
    description: '云端存储空间配额',
    values: {
      [UserTier.FREE]: '100MB',
      [UserTier.PROFESSIONAL]: '10GB',
      [UserTier.TEAM]: '100GB',
      [UserTier.ENTERPRISE]: '无限',
    },
  },
  {
    name: '并发任务数',
    category: FeatureCategory.QUOTA,
    description: '可同时管理的任务数量',
    values: {
      [UserTier.FREE]: '3个',
      [UserTier.PROFESSIONAL]: '20个',
      [UserTier.TEAM]: '100个',
      [UserTier.ENTERPRISE]: '无限',
    },
  },
  
  // 高级功能
  {
    name: 'AI 增强功能',
    category: FeatureCategory.ADVANCED,
    description: 'AI驱动的配置优化和建议',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: true,
      [UserTier.TEAM]: true,
      [UserTier.ENTERPRISE]: true,
    },
  },
  {
    name: '云端备份',
    category: FeatureCategory.ADVANCED,
    description: '配置和数据的云端备份',
    values: {
      [UserTier.FREE]: '-',
      [UserTier.PROFESSIONAL]: '7天',
      [UserTier.TEAM]: '30天',
      [UserTier.ENTERPRISE]: '无限',
    },
  },
  {
    name: '私有云存储',
    category: FeatureCategory.ADVANCED,
    description: '支持私有云存储配置',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: true,
      [UserTier.TEAM]: true,
      [UserTier.ENTERPRISE]: true,
    },
  },
  {
    name: '数据导出',
    category: FeatureCategory.ADVANCED,
    description: '导出所有配置和数据',
    values: {
      [UserTier.FREE]: '基础',
      [UserTier.PROFESSIONAL]: '高级',
      [UserTier.TEAM]: '高级',
      [UserTier.ENTERPRISE]: '企业级',
    },
  },
  
  // 协作功能
  {
    name: '团队协作',
    category: FeatureCategory.COLLABORATION,
    description: '团队成员协作功能',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: false,
      [UserTier.TEAM]: true,
      [UserTier.ENTERPRISE]: true,
    },
    highlight: true,
  },
  {
    name: '团队成员数',
    category: FeatureCategory.COLLABORATION,
    description: '可添加的团队成员数量',
    values: {
      [UserTier.FREE]: '1人',
      [UserTier.PROFESSIONAL]: '1人',
      [UserTier.TEAM]: '3-50人',
      [UserTier.ENTERPRISE]: '50+人',
    },
  },
  {
    name: '权限管理',
    category: FeatureCategory.COLLABORATION,
    description: '细粒度的权限控制',
    values: {
      [UserTier.FREE]: '基础',
      [UserTier.PROFESSIONAL]: '基础',
      [UserTier.TEAM]: '高级',
      [UserTier.ENTERPRISE]: 'RBAC',
    },
  },
  {
    name: '数据可见性',
    category: FeatureCategory.COLLABORATION,
    description: '支持的数据可见性级别',
    values: {
      [UserTier.FREE]: '公开',
      [UserTier.PROFESSIONAL]: '私有/公开',
      [UserTier.TEAM]: '团队内/部门',
      [UserTier.ENTERPRISE]: '5级控制',
    },
  },
  
  // 安全与合规
  {
    name: '审计日志',
    category: FeatureCategory.SECURITY,
    description: '操作审计日志保留',
    values: {
      [UserTier.FREE]: '-',
      [UserTier.PROFESSIONAL]: '-',
      [UserTier.TEAM]: '90天',
      [UserTier.ENTERPRISE]: '365天',
    },
  },
  {
    name: 'SSO 单点登录',
    category: FeatureCategory.SECURITY,
    description: '企业SSO集成',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: false,
      [UserTier.TEAM]: false,
      [UserTier.ENTERPRISE]: true,
    },
  },
  {
    name: 'IP 白名单',
    category: FeatureCategory.SECURITY,
    description: 'IP访问控制',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: false,
      [UserTier.TEAM]: false,
      [UserTier.ENTERPRISE]: true,
    },
  },
  {
    name: '数据加密',
    category: FeatureCategory.SECURITY,
    description: '数据传输和存储加密',
    values: {
      [UserTier.FREE]: '传输',
      [UserTier.PROFESSIONAL]: '传输+存储',
      [UserTier.TEAM]: '传输+存储',
      [UserTier.ENTERPRISE]: '高级加密',
    },
  },
  {
    name: '合规认证',
    category: FeatureCategory.SECURITY,
    description: '符合的合规标准',
    values: {
      [UserTier.FREE]: '-',
      [UserTier.PROFESSIONAL]: '-',
      [UserTier.TEAM]: '基础',
      [UserTier.ENTERPRISE]: 'SOC2/ISO',
    },
  },
  
  // 支持服务
  {
    name: 'SLA 保障',
    category: FeatureCategory.SUPPORT,
    description: '服务可用性保证',
    values: {
      [UserTier.FREE]: '-',
      [UserTier.PROFESSIONAL]: '-',
      [UserTier.TEAM]: '-',
      [UserTier.ENTERPRISE]: '99.9%',
    },
  },
  {
    name: '技术支持',
    category: FeatureCategory.SUPPORT,
    description: '技术支持响应级别',
    values: {
      [UserTier.FREE]: '社区',
      [UserTier.PROFESSIONAL]: '邮件',
      [UserTier.TEAM]: '优先支持',
      [UserTier.ENTERPRISE]: '专属支持',
    },
  },
  {
    name: '响应时间',
    category: FeatureCategory.SUPPORT,
    description: '技术支持响应时间',
    values: {
      [UserTier.FREE]: '3-5天',
      [UserTier.PROFESSIONAL]: '1-2天',
      [UserTier.TEAM]: '4-8小时',
      [UserTier.ENTERPRISE]: '1小时',
    },
  },
  {
    name: '培训服务',
    category: FeatureCategory.SUPPORT,
    description: '团队培训和咨询',
    values: {
      [UserTier.FREE]: false,
      [UserTier.PROFESSIONAL]: '文档',
      [UserTier.TEAM]: '视频教程',
      [UserTier.ENTERPRISE]: '现场培训',
    },
  },
];

/**
 * 功能对比CLI展示
 */
export class FeatureComparisonUI {
  private featureManager: FeatureManager;

  constructor() {
    this.featureManager = new FeatureManager();
  }

  /**
   * 显示完整功能对比表
   */
  displayFullComparison(): void {
    console.log(chalk.bold('\n📊 meteor-shower 功能对比表\n'));
    console.log(chalk.gray('─'.repeat(100)));

    // 按分类显示
    const categories = Object.values(FeatureCategory);
    
    for (const category of categories) {
      this.displayCategory(category);
    }
  }

  /**
   * 显示特定分类的功能对比
   */
  displayCategory(category: FeatureCategory): void {
    const categoryNames = {
      [FeatureCategory.BASIC]: '📦 基础功能',
      [FeatureCategory.QUOTA]: '📊 配额限制',
      [FeatureCategory.ADVANCED]: '⚡ 高级功能',
      [FeatureCategory.COLLABORATION]: '👥 协作功能',
      [FeatureCategory.SECURITY]: '🔒 安全与合规',
      [FeatureCategory.SUPPORT]: '🆘 支持服务',
    };

    const items = FEATURE_COMPARISON.filter(item => item.category === category);
    
    if (items.length === 0) return;

    console.log(chalk.cyan(`\n${categoryNames[category]}`));
    console.log(chalk.gray('─'.repeat(100)));

    // 表头
    console.log(
      this.formatRow(
        '功能',
        '免费版',
        '专业版',
        '团队版',
        '企业版'
      )
    );
    console.log(chalk.gray('─'.repeat(100)));

    // 功能行
    items.forEach(item => {
      const row = this.formatRow(
        item.name,
        this.formatValue(item.values[UserTier.FREE]),
        this.formatValue(item.values[UserTier.PROFESSIONAL]),
        this.formatValue(item.values[UserTier.TEAM]),
        this.formatValue(item.values[UserTier.ENTERPRISE])
      );

      if (item.highlight) {
        console.log(chalk.yellow(row));
      } else {
        console.log(row);
      }
    });

    console.log();
  }

  /**
   * 显示两个层级的对比
   */
  displayTierComparison(tier1: UserTier, tier2: UserTier): void {
    const tierNames = {
      [UserTier.FREE]: '免费版',
      [UserTier.PROFESSIONAL]: '专业版',
      [UserTier.TEAM]: '团队版',
      [UserTier.ENTERPRISE]: '企业版',
    };

    console.log(chalk.bold(`\n📊 ${tierNames[tier1]} vs ${tierNames[tier2]}\n`));
    console.log(chalk.gray('─'.repeat(80)));

    // 表头
    console.log(this.formatComparisonRow('功能', tierNames[tier1], tierNames[tier2], '差异'));
    console.log(chalk.gray('─'.repeat(80)));

    // 显示有差异的功能
    FEATURE_COMPARISON.forEach(item => {
      const value1 = item.values[tier1];
      const value2 = item.values[tier2];

      if (value1 !== value2) {
        const diff = this.calculateDifference(value1, value2);
        console.log(
          this.formatComparisonRow(
            item.name,
            this.formatValue(value1),
            this.formatValue(value2),
            diff
          )
        );
      }
    });

    console.log();
  }

  /**
   * 显示升级建议
   */
  displayUpgradeRecommendation(currentTier: UserTier, targetTier: UserTier): void {
    console.log(chalk.bold(`\n💡 升级到${this.getTierName(targetTier)}后，您将获得:\n`));

    const improvements: string[] = [];

    FEATURE_COMPARISON.forEach(item => {
      const currentValue = item.values[currentTier];
      const targetValue = item.values[targetTier];

      if (this.isImprovement(currentValue, targetValue)) {
        improvements.push(
          `✓ ${item.name}: ${this.formatValue(currentValue)} → ${chalk.green(this.formatValue(targetValue))}`
        );
      }
    });

    improvements.forEach(improvement => console.log(improvement));
    console.log();
  }

  /**
   * 格式化表格行
   */
  private formatRow(...columns: string[]): string {
    const widths = [30, 15, 15, 15, 15];
    return columns
      .map((col, i) => col.padEnd(widths[i]))
      .join(' ');
  }

  /**
   * 格式化对比行
   */
  private formatComparisonRow(...columns: string[]): string {
    const widths = [30, 20, 20, 20];
    return columns
      .map((col, i) => col.padEnd(widths[i]))
      .join(' ');
  }

  /**
   * 格式化值显示
   */
  private formatValue(value: string | number | boolean): string {
    if (typeof value === 'boolean') {
      return value ? chalk.green('✓') : chalk.gray('-');
    }
    if (value === '无限' || value === 'Infinity') {
      return chalk.green('无限');
    }
    if (value === '-' || value === false) {
      return chalk.gray('-');
    }
    return String(value);
  }

  /**
   * 计算差异
   */
  private calculateDifference(value1: any, value2: any): string {
    if (typeof value1 === 'boolean' && typeof value2 === 'boolean') {
      return value2 ? chalk.green('新增') : chalk.red('移除');
    }
    if (value1 === '-' && value2 !== '-') {
      return chalk.green('新增');
    }
    if (value1 !== '-' && value2 === '-') {
      return chalk.red('移除');
    }
    return chalk.yellow('升级');
  }

  /**
   * 判断是否为改进
   */
  private isImprovement(currentValue: any, targetValue: any): boolean {
    if (typeof currentValue === 'boolean' && typeof targetValue === 'boolean') {
      return !currentValue && targetValue;
    }
    if (currentValue === '-' || currentValue === false) {
      return targetValue !== '-' && targetValue !== false;
    }
    return currentValue !== targetValue;
  }

  /**
   * 获取层级名称
   */
  private getTierName(tier: UserTier): string {
    const names = {
      [UserTier.FREE]: '免费版',
      [UserTier.PROFESSIONAL]: '专业版',
      [UserTier.TEAM]: '团队版',
      [UserTier.ENTERPRISE]: '企业版',
    };
    return names[tier];
  }
}
